/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yinliang.ects.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts2.ServletActionContext;



import com.yinliang.ects.dao.impl.ProductDaoImpl;
import com.yinliang.ects.entity.Cart;
import com.yinliang.ects.entity.Product;
import com.yinliang.ects.entity.User;
import com.yinliang.ects.exception.ManagerProductException;


public class CartAction  {
	HttpServletRequest request=ServletActionContext.getRequest();
	public String add() {
		
		
		
		
		
		
		
		String message = null;
		
		HttpSession session=request.getSession();
		String number=request.getParameter("number");
		Cart cart=(Cart) session.getAttribute("cart");
		User user=(User) session.getAttribute("user");
		
		
		
		if(user==null){
			message="您还没有登录,请先登录!";
			
			request.setAttribute("message", message);
			return "failed";
		}
		
		
		if(cart==null){
			message="您还没有登录,请先登录!";
			request.setAttribute("message", message);
			return "failed";
		}
		
		
		ProductDaoImpl productDaoImpl=new ProductDaoImpl();
		String id=request.getParameter("productId");
		Product product=null;
		try {
			product = productDaoImpl.findById(Integer.parseInt(id));
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ManagerProductException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		cart.addItems(product,Integer.parseInt(number));
		session.setAttribute("cart", cart);
		
		
		message="添加商品成功!";
		
		request.setAttribute("message", message);
		return "succeed";
		
		
		
	}
	public String deleteItems() {
		String message = null;
		
		
		HttpSession session=request.getSession();
		Cart cart=(Cart) session.getAttribute("cart");
		
		
		
		if(request.getParameter("deleteAll")!=null){
			cart.removeAll();
			session.setAttribute("cart", cart);
			message="删除所有项目成功!";
			request.setAttribute("message", message);
			session.setAttribute("cart", cart);
			return "succeed";
		}
		
		
		
		Product product=null ;
		int productId=Integer.parseInt(request.getParameter("itemKeyId"));
		
		ProductDaoImpl productDaoImpl=new ProductDaoImpl();
		try {
			product=productDaoImpl.findById(productId);
			cart.removeItems(product);
			message="删除项目成功!";
			
			request.setAttribute("message", message);
			session.setAttribute("cart", cart);
			return "succeed";
		} catch (ManagerProductException e) {
			message="删除项目失败!";
			request.setAttribute("message", message);
			return "failed";
		}
		
		
		
		
		
		
		
		
		
		
	}
}



















