/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yinliang.ects.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts2.ServletActionContext;


import com.yinliang.ects.dao.impl.ProductDaoImpl;
import com.yinliang.ects.entity.Product;
import com.yinliang.ects.exception.ManagerProductException;


public class ProductAction  {
	HttpServletRequest request=ServletActionContext.getRequest();
	
	
	public String FindAll() {
		String message = null;
		
		ProductDaoImpl productDaoImpl=new ProductDaoImpl();
		int nowCount=1;
		int pageCount=0;
		List<Product>productsList=null;
		
		if(request.getParameter("pageCount")!=null){
			pageCount=Integer.parseInt(request.getParameter("pageCount"));
		}else {
			try {
				pageCount=productDaoImpl.getPageCount();
			} catch (ManagerProductException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		if(request.getParameter("nowCount")!=null){
			nowCount=Integer.parseInt(request.getParameter("nowCount"));
			if(nowCount<1){
				nowCount=1;
			}
			if(nowCount>pageCount){
				nowCount=pageCount;
			}
		}
		try {
			productsList=(List<Product>) productDaoImpl.findByPageId(nowCount);
			message="当前页查找成功!";
			request.setAttribute("message", message);
			request.setAttribute("pageCount", pageCount);
			request.setAttribute("productsList", productsList);
			request.setAttribute("nowCount", nowCount);
			return "succeed";
			
		} catch (ManagerProductException e) {
			message="数据加载失败!";
			request.setAttribute("message", message);
			request.setAttribute("pageCount", pageCount);
			request.setAttribute("productsList", productsList);
			request.setAttribute("nowCount", nowCount);
			return "failed";
		}
	}
	public String  FindProductDetails() {
		String message = null;
		
		Product product=null;
		String productId=request.getParameter("productId");
		ProductDaoImpl productDaoImpl=new ProductDaoImpl();
		try {
			product=productDaoImpl.findById(Integer.parseInt(productId));
			String img=product.getImages().replace(".jpg", "b.jpg");
			product.setImages(img);
			request.setAttribute("product", product);
			message="查看产品详情成功!";
			request.setAttribute("message", message);
			return "succeed";
		} catch (NumberFormatException e) {
			message="数据加载失败";
			request.setAttribute("message", message);
			return "failed";
		} catch (ManagerProductException e) {
			message="数据加载失败";
			
			request.setAttribute("message", message);
			return "failed";
		}
		
		
	}
	
	
}